AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the {{ resource_type }} resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 256

Resources:
  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      {% for key, value in test_handler_params.items() %}
      {{ key }}: {{ value }}
      {% endfor %}

  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      {% for key, value in handler_params.items() %}
      {{ key }}: {{ value }}
      {% endfor %}
    Metadata:
      BuildMethod: makefile
